# This is the default format. 
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /:categories/:year/:month/:day/:title 

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
highlighter: rouge

# Themes are encouraged to use these universal variables 
# so be sure to set them if your theme uses them.
#
title: Hi, I'm Chen Chun
description: '#Kubernetes #Docker #Kernel #Network #Hadoop'
author :
  name : Chen Chun
  email : chenchun.feed@gmail.com
  github : chenchun
  feedburner : feedname

theme: jekyll-theme-cayman
markdown: kramdown
